### ISSUE TITLE
xyDragComponent, return to default

### ISSUE THREAD

**Issue by Werner88** [ffAudio/foleys_gui_magic#36] opened 2020-04-05 09:54 UTC
(Mac, XCode 10.1, Standalone-Build)
1)
in 1.10 here the xyDragComponent never paints the parameters.
When bringing the old code back to line 410 in foleysMagicJuceFactories.cpp
it works again:
instead of just //return std::unique_ptr<XYDragComponent>();
                       ```
                         if (auto* magicState = getProcessorState())
                         {
                             auto item = std::make_unique<XYDragComponent>(magicState->getValueTreeState());
                             
                             auto paramX = config.getProperty (IDs::parameterX).toString();
                             if (paramX.isNotEmpty())
                                 item->setParameterX (paramX);
                             
                             auto paramY = config.getProperty (IDs::parameterY).toString();
                             if (paramY.isNotEmpty())
                                 item->setParameterY (paramY);
                             
                             return std::move (item);
                         }
                         else
                         {
                             return std::unique_ptr<XYDragComponent>();
                         }
```
2)
if a colourSelect field "x"-Button  in the Editor-Tool is not editable, and you change the fields value (set a new colour), after that you are not able to return to the default value, because the "x" Button is still not enabled. After selecting another node and coming back the "x" Button is enabled and you can return to the default value.

**Comment by ffAudio** [comment] 2020-04-07 10:38
This is a duplicate of #37

**Closed by ffAudio** 2020-04-07 10:38 UTC
